name: "Deploy"

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CI: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  deploy:
    name: "Deploy"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup pnpm"
        uses: pnpm/setup@v2.2.4
        with:
          version: latest

      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: "lts/*"

      - name: "Install Dependencies"
        run: pnpm install

      - name: "Build"
        run: pnpm build

      - name: "Deploy"
        # TODO: Deploy
        run: |
          echo 'TODO: Deploy'
